name: Patch compose-unpacker and build Docker image

on:
  workflow_dispatch:
    inputs:
      portainer_tag:
        description: The Portainer tag to base the image on
        required: true

jobs:
  patch-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Patch compose-unpacker and build Docker image
        uses: ./.github/actions/patch-build
        with:
          portainer_tag: ${{ inputs.portainer_tag }}
          image_tag: ${{ inputs.portainer_tag }}-test
